synesthesia-project/synesthesia

balccon/src/index.ts, common/config/rush/pnpm-lock.yaml, composer/src/integration/shared.ts, composer/src/scripts/ts/components/toolbar.tsx, composer/src/scripts/ts/components/util/file-controller.ts, composer/src/scripts/ts/sources/integration-source.ts, core/examples/consumer/src/main.ts, core/examples/controller/src/components/stage.tsx, core/examples/playlist-controller/src/components/stage.tsx, core/package.json, core/src/lib/local/index.ts, core/src/lib/protocols/broadcast/downstream.ts, core/src/lib/protocols/broadcast/upstream.ts, core/src/lib/protocols/control/controller.ts, core/src/lib/protocols/control/messages.ts, core/src/lib/protocols/control/server.ts, core/src/lib/protocols/util/connection-metadata.ts, core/src/lib/protocols/util/endpoint.ts, core/src/lib/protocols/util/messages.ts, server/src/main/connections/composer.ts, server/src/main/connections/controller.ts, server/src/main/connections/downstream.ts, server/src/main/server.ts, server/src/main/state/state.ts, synesthesia-razer/src/index.ts
=> Introduce connection metadata layer

composer/src/scripts/ts/components/integration-button.tsx, composer/src/scripts/ts/components/item-properties.tsx
#76 check it i changes two files
composer/src/scripts/ts/components/integration-button.tsx
composer/src/scripts/ts/components/item-properties.tsx
after changes i did rush lint:fix
=> done rush lint:fix + replace binds with arrow function

core/src/lib/local/index.ts, server/src/main/server.ts
=> Remove last remaining binds

composer/src/scripts/ts/components/integration-button.tsx, composer/src/scripts/ts/sources/integration-source.ts
=> Rewrite IntegrationButton as functional component

composer/src/scripts/ts/components/layer-visualization.tsx
=> Rewrite LayerVisualization as functional component

composer/src/scripts/ts/components/item-properties.tsx, composer/src/scripts/ts/components/layer-items.tsx, composer/src/scripts/ts/components/layer.tsx
=> Rewrite 3 more components as functional components

composer/src/scripts/ts/components/layers-and-timeline.tsx, composer/src/scripts/ts/components/util/debounce.ts
=> Rewrite LayersAndTimeline as a functional component

light-desk/src/backend/components/base.ts, light-desk/src/backend/components/group.ts, light-desk/src/backend/components/tabs.ts, light-desk/src/backend/index.ts, light-desk/src/frontend/components/group.tsx, light-desk/src/frontend/components/nesting.tsx, light-desk/src/frontend/components/stage.tsx, light-desk/src/frontend/components/tabs.tsx, light-desk/src/shared/proto.ts, live/app/src/desk/desk.ts
=> Introduce new tabs component and use at top level of live desk

light-desk/CHANGELOG.md, light-desk/src/backend/components/group.ts, light-desk/src/frontend/components/group.tsx, light-desk/src/shared/proto.ts, live/app/src/stage.ts
=> live-desk: introduce labels and use them in live outputs

light-desk/CHANGELOG.md, light-desk/src/backend/components/base.ts, light-desk/src/backend/components/button.ts, light-desk/src/backend/components/group.ts, light-desk/src/frontend/components/group.tsx, light-desk/src/shared/proto.ts, live/app/src/inputs.ts, live/app/src/stage.ts
=> Introduce group header buttons and use in live

compositor/src/lib/modules/chase.ts, live/app/src/index.ts, live/app/src/plugins/add-input.ts, live/app/src/plugins/chase-input.ts
closes https://github.com/synesthesia-project/synesthesia/issues/126
=> Introduce new chase input kind and plugin 

light-desk/CHANGELOG.md, light-desk/src/backend/components/base.ts, light-desk/src/backend/components/group.ts, light-desk/src/frontend/components/group.tsx, light-desk/src/frontend/components/icon.tsx, light-desk/src/shared/proto.ts, live/app/src/stage.ts, live/core/src/util.ts
=> make group titles optionally editable, and use for renaming outputs

common/config/rush/pnpm-lock.yaml, live/app/package.json, live/app/src/config.ts, live/app/src/desk/desk.ts, live/app/src/stage.ts, live/core/src/config.ts, live/dmx/package.json, live/dmx/src/index.ts
Introduces UUIDs and uses them for output keys and dmx output fixtures.
Closes #136
=> Output uuids

light-desk/src/backend/components/base.ts, live/dmx/src/index.ts
=> live-dmx: allow fixtures to be named

light-desk/src/backend/components/text-input.ts, live/app/src/stage.ts, live/dmx/src/index.ts
Closes #139 
Allow additional channels to be added to fixtures, and allow for them to be named and for their value to be set (this will be followed by a way to link their values to a sequence).
=> Introduce additional (non-compositor) DMX channels

light-desk/src/backend/index.ts, light-desk/src/frontend/components/label.tsx, live/app/src/config.ts, live/app/src/desk/desk.ts, live/app/src/desk/tree-selector.ts, live/app/src/sequences/index.ts, live/app/src/stage.ts, live/core/src/plugins/index.ts, live/dmx/src/index.ts
=> Introduce groups and sequences, and allow registering channels and adding them to groups

light-desk/CHANGELOG.md, light-desk/src/backend/components/button.ts, light-desk/src/frontend/components/button.tsx, light-desk/src/shared/proto.ts, live/app/src/config.ts, live/app/src/desk/desk.ts, live/app/src/sequences/index.ts, live/app/src/stage.ts, live/core/src/plugins/index.ts, live/dmx/src/index.ts
Allow switching sequences, setting sequence channel values, and using these values in dmx.
=> More sequence implementation

light-desk/src/backend/components/group.ts, live/app/src/config.ts, live/app/src/inputs.ts, live/app/src/stage.ts, live/core/src/plugins/index.ts
=> Various improvements to cues

light-desk/CHANGELOG.md, light-desk/src/backend/components/group.ts, light-desk/src/frontend/components/button.tsx, light-desk/src/frontend/components/group.tsx, light-desk/src/frontend/components/stage.tsx, light-desk/src/frontend/util/touch.ts, light-desk/src/shared/proto.ts, live/app/src/inputs.ts, live/app/src/sequences/index.ts, live/app/src/stage.ts, live/dmx/src/index.ts
=> Introduce collapsible groups and use them in live-app

light-desk/src/frontend/components/slider_button.tsx, light-desk/src/frontend/util/touch.ts, light-desk/src/frontend/util/util.ts, live/dmx/src/index.ts
Fix touch bugs (#151) and other misc improvements to slider button.
closes #151
=> Touch bug fixes and slider button improvements.

light-desk/src/backend/components/slider_button.ts, light-desk/src/frontend/components/slider_button.tsx
Modify the behaviour of slider buttons when using a mouse and keyboard to allow for manual value entering, and also fin (step) adjustment using arrow keys.
fixes #150
=> Manual adjustment for slider buttons

live/app/src/stage.ts, live/dmx/src/index.ts, live/dmx/src/universes.ts
=> live-dmx: improve definitions of dmx universes

live/app/src/plugins/virtual-output.ts, live/app/src/stage.ts, live/core/src/plugins/index.ts, live/dmx/src/fixtures/custom.ts, live/dmx/src/fixtures/rgb-strip.ts, live/dmx/src/fixtures/types.ts, live/dmx/src/index.ts, live/dmx/src/universes.ts, live/dmx/src/util.ts
fixes https://github.com/synesthesia-project/synesthesia/issues/156
=> live-dmx: Introduce LED strip DMX configuration

compositor/src/lib/modules/scan.ts, live/app/src/index.ts, live/app/src/plugins/scan-input.ts
=> live-app: add scan compositor module

common/config/rush/pnpm-lock.yaml, live/app/package.json, live/app/src/desk/desk.ts, live/app/src/index.ts, live/app/src/plugins/bpm/index.ts, live/app/src/stage.ts, live/core/package.json, live/core/src/actions.ts, live/core/src/events.ts, live/core/src/plugins/index.ts
=> Introduce Actions, Events and manual BPM input

live/app/src/config/index.ts, live/app/src/config/plugins.ts, live/app/src/inputs.ts, live/app/src/plugins/add-input.ts, live/app/src/plugins/beat-input.ts, live/app/src/plugins/chase-input.ts, live/app/src/plugins/fill-input.ts, live/app/src/plugins/scan-input.ts, live/app/src/plugins/virtual-output.ts, live/app/src/stage.ts, live/core/src/plugins/index.ts, live/core/src/util.ts, live/dmx/src/index.ts
closes https://github.com/synesthesia-project/synesthesia/issues/168
=> Refactor config and allow plugin config

light-desk/src/backend/components/base.ts, light-desk/src/backend/components/button.ts, light-desk/src/backend/components/group.ts, light-desk/src/backend/components/slider_button.ts, light-desk/src/backend/components/switch.ts, light-desk/src/backend/components/text-input.ts, light-desk/src/backend/index.ts
=> Light desk fixes

live/dmx/src/universes.ts
Fix bug where config would be updated during construction, affecting other parts of the app
=> fix config bug caused by dmx universes plugin

live/app/src/index.ts, live/app/src/plugins/filter-input.ts, live/dmx/src/index.ts
=> Add fixture properties and filter module

live/app/src/plugins/beat-input.ts, live/app/src/plugins/bpm/index.ts
=> BPM / Beat improvements
